// examples/react-todo/src/App.tsx
import { useState } from 'react'
import { createTodo, toggleTodo, deleteTodo } from './todos'

export default function App() {
  const [todos, setTodos] = useState([])
  const [input, setInput] = useState('')

  function handleAdd() {
    if (!input.trim()) return
    setTodos([...todos, createTodo(input)])
    setInput('')
  }

  function handleToggle(todo) {
    setTodos(todos.map(function (t) { return t.id === todo.id ? toggleTodo(t) : t }))
  }

  function handleDelete(id) {
    setTodos(deleteTodo(todos, id))
  }

  return (
    <div>
      <h1>React Todos</h1>
      <div className="input-row">
        <input value={input} onChange={function (e) { return setInput(e.target.value) }} onKeyDown={function (e) { if (e.key === 'Enter') handleAdd() }} placeholder="What needs to be done?" />
        <button className="add-btn" onClick={handleAdd}>Add</button>
      </div>
      {todos.length === 0 ? (
        <p className="empty">No todos yet. Add one above!</p>
      ) : (
        <ul className="todo-list">
          {todos.map(function (todo) {
            return (
              <li key={todo.id} className="todo-item">
                <input type="checkbox" checked={todo.completed} onChange={function () { return handleToggle(todo) }} />
                <span className={'todo-text' + (todo.completed ? ' done' : '')} onClick={function () { return handleToggle(todo) }}>{todo.text}</span>
                <button className="del-btn" onClick={function () { return handleDelete(todo.id) }}>{'\u00d7'}</button>
              </li>
            )
          })}
        </ul>
      )}
    </div>
  )
}

// examples/vue-todo/src/App.vue
<template>
  <div>
    <h1>Vue Todos</h1>
    <div class="input-row">
      <input v-model="inputText" @keyup.enter="handleAdd" placeholder="What needs to be done?">
      <button class="add-btn" @click="handleAdd">Add</button>
    </div>
    <p v-if="todos.length === 0" class="empty">No todos yet. Add one above!</p>
    <ul v-else class="todo-list">
      <li v-for="todo in todos" :key="todo.id" class="todo-item">
        <input type="checkbox" :checked="todo.completed" @change="handleToggle(todo)">
        <span :class="['todo-text', { done: todo.completed }]" @click="handleToggle(todo)">{{ todo.text }}</span>
        <button class="del-btn" @click="handleDelete(todo.id)">×</button>
      </li>
    </ul>
  </div>
</template>

<script>
import { createTodo, toggleTodo, deleteTodo } from './todos'

export default {
  data() {
    return {
      todos: [],
      inputText: ''
    }
  },
  methods: {
    handleAdd() {
      if (!this.inputText.trim()) return
      this.todos.push(createTodo(this.inputText))
      this.inputText = ''
    },
    handleToggle(todo) {
      const idx = this.todos.findIndex(function (t) { return t.id === todo.id })
      if (idx !== -1) this.todos[idx] = toggleTodo(todo)
    },
    handleDelete(id) {
      this.todos = deleteTodo(this.todos, id)
    }
  }
}
</script>
